// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vendas.DAL;

namespace Vendas.DAL.Core.Migrations
{
    [DbContext(typeof(BancoDeDadosContext))]
    [Migration("20220623103403_CRIACAO_VENDA_ITEM-VENDA")]
    partial class CRIACAO_VENDA_ITEMVENDA
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Vendas.DAL.ItemDaVendaService", b =>
                {
                    b.Property<int>("CodigoDoItem")
                        .HasColumnType("int");

                    b.Property<int>("CodigoDaVenda")
                        .HasColumnType("int");

                    b.Property<int?>("ProdutoCodigo")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<double>("ValorTotal")
                        .HasColumnType("double");

                    b.Property<int?>("VendaServiceCodigo")
                        .HasColumnType("int");

                    b.HasKey("CodigoDoItem", "CodigoDaVenda");

                    b.HasIndex("ProdutoCodigo");

                    b.HasIndex("VendaServiceCodigo");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("Vendas.DAL.ProdutoService", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<double>("ValorUnitario")
                        .HasColumnType("double");

                    b.HasKey("Codigo");

                    b.ToTable("varProduto");
                });

            modelBuilder.Entity("Vendas.DAL.VendaService", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataDaVenda")
                        .HasColumnType("datetime");

                    b.HasKey("Codigo");

                    b.ToTable("Venda");
                });

            modelBuilder.Entity("Vendas.DAL.ItemDaVendaService", b =>
                {
                    b.HasOne("Vendas.DAL.ProdutoService", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoCodigo");

                    b.HasOne("Vendas.DAL.VendaService", null)
                        .WithMany("ItensDaLista")
                        .HasForeignKey("VendaServiceCodigo");
                });
#pragma warning restore 612, 618
        }
    }
}
