// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vendas.DAL;

namespace Vendas.DAL.Core.Migrations
{
    [DbContext(typeof(BancoDeDadosContext))]
    [Migration("20220613112748_CRIACAO_DB")]
    partial class CRIACAO_DB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Vendas.DAL.ProdutoService", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<double>("ValorUnitario")
                        .HasColumnType("double");

                    b.HasKey("Codigo");

                    b.ToTable("varProduto");
                });
#pragma warning restore 612, 618
        }
    }
}
